<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		array(
			'name'=>'DESAID',
			'value'=>$model->dESA->nama,
		),
		array(
			'name'=>'R301',
			'value'=>$model->r301->nama,
		),
		'R302A',
		'NAMA_PULAU',
		array(
			'name'=>'R304A',
			'value'=>$model->r304A->nama,
		), 		 		
		array(
			'name'=>'R305A',
			'value'=>$model->r305A->nama,
		),
		array(
			'name'=>'R305B',
			'value'=>$model->r305B->nama,
		),
		array(
			'name'=>'R305D',
			'value'=>$model->r305D->nama,
		),
		array(
			'name'=>'R305E1',
			'value'=>$model->r305E1->nama,
			'visible'=>($model->R305D==1),
		),
		array(
			'name'=>'R305E2A',
			'value'=>$model->r305E2A->nama,
			'visible'=>($model->R305D==1),
		),
		array(
			'name'=>'R305E2B',
			'value'=>$model->r305E2B->nama,
			'visible'=>($model->R305D==1),
		),
		array(
			'name'=>'R305E2C',
			'value'=>$model->r305E2C->nama,
			'visible'=>($model->R305D==1),
		),
		array(
			'name'=>'R305E2D',
			'value'=>$model->r305E2D->nama,
			'visible'=>($model->R305D==1),
		),
		array(
			'name'=>'R305E2E',
			'value'=>$model->r305E2E->nama,
			'visible'=>($model->R305D==1),
		),
		array(
			'name'=>'R305E3',
			'value'=>$model->r305E3->nama,
		),
		'R305E3',
		array(
			'name'=>'R306A',
			'value'=>$model->r306A->nama,
		),
		array(
			'name'=>'R306B',
			'value'=>$model->r306B->nama,
		),
	),
)); ?>