<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		array(
			'name'=>'DESAID',
			'value'=>$model->dESA->nama,
		),
		array(
			'name'=>'R1205A',
			'value'=>$model->R1205A,
		),
		array(
			'name'=>'R1205B',
			'value'=>$model->R1205B,
		),
		array(
			'name'=>'R1206',
			'value'=>$model->R1206,
		),
		array(
			'name'=>'R1207',
			'value'=>$model->R1207,
		),
		array(
			'name'=>'R1208',
			'value'=>$model->R1208,
		),
		array(
			'name'=>'R1209',
			'value'=>$model->R1209,
		),
		array(
			'name'=>'R1210',
			'value'=>$model->R1210,
		),
	),
)); ?> 