<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		array(
			'name'=>'DESAID',
			'value'=>$model->dESA->nama,
		),
		array(
			'name'=>'R803A',
			'value'=>$model->R803A,
		),
		array(
			'name'=>'R803B',
			'value'=>$model->R803B,
		),
		array(
			'name'=>'R803C',
			'value'=>$model->R803C,
		),
		array(
			'name'=>'R803D',
			'value'=>$model->R803D,
		),
		array(
			'name'=>'R803E',
			'value'=>$model->R803E,
		),
		array(
			'name'=>'R803F',
			'value'=>$model->R803F,
		),
		array(
			'name'=>'R803G',
			'value'=>$model->R803G,
		),
		array(
			'name'=>'R803H',
			'value'=>$model->R803H,
		),
		array(
			'name'=>'R805A',
			'value'=>$model->R805A,
		),
		array(
			'name'=>'R805B',
			'value'=>$model->R805B,
		),
		array(
			'name'=>'R805C',
			'value'=>$model->R805C,
		),
		array(
			'name'=>'R805D',
			'value'=>$model->R805D,
		),
		array(
			'name'=>'R805E',
			'value'=>$model->R805E,
		),
		array(
			'name'=>'R805F',
			'value'=>$model->R805F,
		),
		array(
			'name'=>'R805G',
			'value'=>$model->R805G,
		),
		array(
			'name'=>'R805H',
			'value'=>$model->R805H,
		),
		array(
			'name'=>'R805I',
			'value'=>$model->R805I,
		),
	),
)); ?> 